GET http://localhost:5005/.well-known/openid-configuration

POST http://localhost:5005/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&scope=movieAPI
&client_id=movieClient
&client_secret=secret

GET http://localhost:5001/api/identity
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5QzlGOEIzNjA1QzQzMTU5M0VBNUI2ODBFMkJEQUJEIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NTA2OTc5MzAsImV4cCI6MTY1MDcwMTUzMCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDA1IiwiY2xpZW50X2lkIjoibW92aWVDbGllbnQiLCJqdGkiOiJEMEYxMURGRjU4RUY5QkExNjdDQUM0Njc1Q0EzNkRDQSIsImlhdCI6MTY1MDY5NzkzMCwic2NvcGUiOlsibW92aWVBUEkiXX0.CrFC7Dzatn6zN8dbkfb5WHUtm1C97_-wkBphP19W6MGRUtgoe4JG_JHZt-5ZYNrefGV8SIFObGtK1YHykiUVyNQoN3-5ki92AsAs4auWNd4u3xlhIXUFT5TKdmCpR7g0B_2BmVu0Nwkb_WwrWWa2speQRvpRIt4BjcWj8Wp8gt0v7QrCtMDpvAg-IXfMUyJDskBsKeX4NAvI_HcNKA-36NTgwLfCqs7AAICw8qMQUZFs2ezEDmIY6Ni06gpTHHmvVq9Y6Ndt3K2nQvQkexs0VeaE12KCtuAf18DTG4FFuY6kbl1DJJAjqOkJk5dUl5Vb1Qqo20AiyZFmHVYeFIESQg 
