POST http://localhost:5005/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&scope=movieAPI
&client_id=movieClient
&client_secret=secret

###

GET http://localhost:5001/api/movies
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5QzlGOEIzNjA1QzQzMTU5M0VBNUI2ODBFMkJEQUJEIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NTA3MjQxNDcsImV4cCI6MTY1MDcyNzc0NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDA1IiwiY2xpZW50X2lkIjoibW92aWVDbGllbnQiLCJqdGkiOiI5MDMxMzA3RTc3Q0M5NTYzQTg0NThERDBGNTAzQ0VBNCIsImlhdCI6MTY1MDcyNDE0Nywic2NvcGUiOlsibW92aWVBUEkiXX0.aCOiAVeFBFgca35AS53OhBKUZobST72RSte5iiGLfopVAx-7oxvj1WyYpiOQVwiPrPMw6QIL7BNqB5_rdWWVExyWXRTzNLzQ_bYhWFuVebZ8WMy5FbgdRW_VjRlZfX6KSWdYQQxPmIQYxysAfYSShgHm-CqAdPfOYObA7hMwdejwjw5eHiHBortfW3op5NQzPrB-8ODJDtRCwnvVsOGea1myxjeXA3F57QpBM9RAAfIkeQ9E22DPt4WujcRvHOe2wSE9R034M92Y--Xc7IWO31HZwj8VIj_Hr26Lv0Dr_CZJ3boLCdAGFbR1bmrR-HAkeEWXzdK1Q1xwd_ZBWyE9vg 

GET http://localhost:5001/api/movies/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5QzlGOEIzNjA1QzQzMTU5M0VBNUI2ODBFMkJEQUJEIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NTA3MjQxNDcsImV4cCI6MTY1MDcyNzc0NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDA1IiwiY2xpZW50X2lkIjoibW92aWVDbGllbnQiLCJqdGkiOiI5MDMxMzA3RTc3Q0M5NTYzQTg0NThERDBGNTAzQ0VBNCIsImlhdCI6MTY1MDcyNDE0Nywic2NvcGUiOlsibW92aWVBUEkiXX0.aCOiAVeFBFgca35AS53OhBKUZobST72RSte5iiGLfopVAx-7oxvj1WyYpiOQVwiPrPMw6QIL7BNqB5_rdWWVExyWXRTzNLzQ_bYhWFuVebZ8WMy5FbgdRW_VjRlZfX6KSWdYQQxPmIQYxysAfYSShgHm-CqAdPfOYObA7hMwdejwjw5eHiHBortfW3op5NQzPrB-8ODJDtRCwnvVsOGea1myxjeXA3F57QpBM9RAAfIkeQ9E22DPt4WujcRvHOe2wSE9R034M92Y--Xc7IWO31HZwj8VIj_Hr26Lv0Dr_CZJ3boLCdAGFbR1bmrR-HAkeEWXzdK1Q1xwd_ZBWyE9vg 

###

POST https://localhost:5001/api/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc5QzlGOEIzNjA1QzQzMTU5M0VBNUI2ODBFMkJEQUJEIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE2NTA2Mjg5NDAsImV4cCI6MTY1MDYzMjU0MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwNSIsImNsaWVudF9pZCI6Im1vdmllQ2xpZW50IiwianRpIjoiMkQxRDJDQ0EyQUQ4M0EwQzY2MEZGRThFMEQwREM4NzUiLCJpYXQiOjE2NTA2Mjg5NDAsInNjb3BlIjpbIm1vdmllQVBJIl19.dT9ZK4EtpVBIYMB6aMES80-WRl2lbRPAZBVi3LWq1QndCcfKWIWEwiR_07j0D9sKghwkqYrOQVKzeJZTBPCOM_81RL5gknSMr4382feSXCErCreKWBol7iIbnx3yQSeAlZGiadOBy_Tyfn7czatqQtj9vWtejwuhSxEtwji3alkVvC2CnKg86XRpqCvIM75npfaZ5mcP8X67LrvIC7h4JrBpVIvqvdaLHQP_pMsAxOIfAqboQ3zABRzjpGxlEiHlEq4HuHZHzuObskn3Itol7-1rHN88uI10MKZwZbrB-TkCix43o9uXAvFAFFT1wDBbkjm31xDzePdPHZSRM1swBA

{
  "id": 9,
  "title": "asd2",
  "genre": "Comics",
  "rating": "9.2",
  "releaseDate": "2020-08-27T16:17:24.4346957+03:00",
  "imageUrl": "images/src",
  "owner": "swn"
}

PUT https://localhost:5001/api/movies/1
Content-Type: application/json

{
  "id": 1,
  "title": "asd22",
  "genre": "Comics",
  "rating": "9.2",
  "releaseDate": "2020-08-27T16:17:24.4346957+03:00",
  "imageUrl": "images/src",
  "owner": "swn"
}

DELETE https://localhost:5001/api/movies/9
